version: '2.1'
services:  
  cache:
    image: mwangxx/redis:5.0.8
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"
  elasticsearch:
    container_name: elasticsearch
    image: mwangxx/elasticsearch:7.6.0
    volumes:
      - $HOME/BulletJournal/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - $HOME/docker/volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms128m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    volumes:
      - $HOME/BulletJournal/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch